# Global Application Configuration

[settings]
# Global application settings
app_name = "{{ app_name }}"

[azure]
# Azure region to deploy to
location = "{{ azure_location }}"


[api]
# Global API configuration
timeout_seconds = 30
retry_attempts = 3
